/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AlunoDao;
import dao.TurmaDao;
import java.awt.BorderLayout;
import java.awt.*;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import model.Aluno;
import utils.ButtonUtils;
import utils.TextFieldUtils;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Turma;
/**
 *
 * @author lucelia
 */
public class CadastroTurmas extends javax.swing.JFrame {
        private List<JCheckBox> checkboxes = new ArrayList<>();
    /**
     * Creates new form DashboardView
     */
    public CadastroTurmas() {
        initComponents();
       padraoPagina();
       preencherAlunos();
       
    }
    private Turma turmaEmEdicao;
    public CadastroTurmas(Turma turma) {
       initComponents();
       padraoPagina();
       this.turmaEmEdicao = turma;
       preencherAlunosExistentes();
    
        if (turma != null) {
            nomeFields.setText(turma.getNome());
        }
    
    }
    
    private void preencherAlunosExistentes() {
        AlunoDao dao = new AlunoDao();

       // 🔹 Buscar alunos da turma atual
       List<Aluno> alunosDaTurma = dao.listarAlunosPorTurma(turmaEmEdicao.getIdTurma());

       // 🔹 Buscar também alunos da turma padrão (sem turma ou turma 1)
       List<Aluno> alunosPadrao = dao.listarAlunosDaTurmaPadrao();

       // 🔹 Combinar as duas listas
       List<Aluno> todosAlunos = new ArrayList<>();
       todosAlunos.addAll(alunosDaTurma);
       todosAlunos.addAll(alunosPadrao);

       // 🔹 Limpar painel e lista de checkboxes
       alunosPainel.removeAll();
       checkboxes.clear();

       // 🔹 Criar checkboxes para cada aluno
       for (Aluno a : todosAlunos) {
           JCheckBox cb = new JCheckBox(a.getNome());
           cb.setBackground(new Color(255, 219, 255));
           cb.putClientProperty("id_aluno", a.getIdAluno());

           // ✅ Marcar se o aluno pertence à turma em edição
           if (a.getIdTurma() == turmaEmEdicao.getIdTurma()) {
               cb.setSelected(true);
           }

           checkboxes.add(cb);
           alunosPainel.add(cb);
       }

       alunosPainel.revalidate();
       alunosPainel.repaint();
   }

    
    
    private void padraoPagina(){
            setSize(800, 650);
        setLocationRelativeTo(null);
        
        getContentPane().setBackground(new Color(200,162,200));
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
      
        
        
        ImageIcon sairIco = new ImageIcon(getClass().getResource("/img/sair.png"));
        ImageIcon corujaIcoLogo = new ImageIcon(getClass().getResource("/img/coruja.png"));
        ImageIcon corujaIco1 = new ImageIcon(getClass().getResource("/img/coruja01.png"));
        
        Image imgSairIco = sairIco.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        Image imgCorujaLogo = corujaIcoLogo.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        Image imgCorujaIco01 = corujaIco1.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        
        imgSair.setIcon(new ImageIcon(imgSairIco));
        
        imgCoruja1.setText(null);
        imgCoruja1.setIcon(new ImageIcon(imgCorujaLogo));
        
        
        imgCoruja2.setText(null);
       imgCoruja2.setIcon(new ImageIcon(imgCorujaIco01));
    
    }
    private void preencherAlunos() {
        AlunoDao dao = new AlunoDao();
        List<Aluno> alunos = dao.listarAlunosDaTurmaPadrao();
        alunosPainel.removeAll();
        checkboxes.clear();

        for (Aluno a : alunos) {
            JCheckBox cb = new JCheckBox(a.getNome());
            cb.setBackground(new Color(255, 219, 255));
            cb.putClientProperty("id_aluno", a.getIdAluno());
            checkboxes.add(cb);
            alunosPainel.add(cb);
        }

      
        alunosPainel.revalidate();
        alunosPainel.repaint();
    }
    

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Salvar = new javax.swing.JButton();
        Salvar2 = new javax.swing.JButton();
        Salvar1 = new javax.swing.JButton();
        Salvar3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imgCoruja1 = new javax.swing.JLabel();
        lblAlunos = new javax.swing.JLabel();
        lblTurmas = new javax.swing.JLabel();
        imgSair = new javax.swing.JLabel();
        imgCoruja2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nomeFields = new javax.swing.JTextField();
        salvarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        listarBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        alunosPainel = new javax.swing.JPanel();

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel3.setText("Cadastro de Alunos");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Nome:");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        Salvar.setBackground(new java.awt.Color(200, 162, 200));
        Salvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Salvar.setText("Salvar");
        Salvar.setBorder(null);
        Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Salvar2.setBackground(new java.awt.Color(200, 162, 200));
        Salvar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salvar2.setForeground(new java.awt.Color(255, 255, 255));
        Salvar2.setText("Excluir");
        Salvar2.setBorder(null);
        Salvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar2ActionPerformed(evt);
            }
        });

        Salvar1.setBackground(new java.awt.Color(200, 162, 200));
        Salvar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salvar1.setForeground(new java.awt.Color(255, 255, 255));
        Salvar1.setText("Cancelar");
        Salvar1.setBorder(null);
        Salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar1ActionPerformed(evt);
            }
        });

        Salvar3.setBackground(new java.awt.Color(200, 162, 200));
        Salvar3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salvar3.setForeground(new java.awt.Color(255, 255, 255));
        Salvar3.setText("Listar Alunos");
        Salvar3.setBorder(null);
        Salvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Data de Nascimento:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 219, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 219, 255));

        jPanel2.setBackground(new java.awt.Color(200, 162, 200));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        imgCoruja1.setText("coruja01");
        imgCoruja1.setMaximumSize(new java.awt.Dimension(150, 150));
        imgCoruja1.setMinimumSize(new java.awt.Dimension(150, 150));
        imgCoruja1.setPreferredSize(new java.awt.Dimension(150, 150));

        lblAlunos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAlunos.setForeground(new java.awt.Color(255, 255, 255));
        lblAlunos.setText("Alunos");
        lblAlunos.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblTurmas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTurmas.setForeground(new java.awt.Color(255, 255, 255));
        lblTurmas.setText("Turmas");

        imgSair.setText("sair");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imgCoruja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imgCoruja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAlunos)
                .addGap(157, 157, 157)
                .addComponent(lblTurmas)
                .addGap(170, 170, 170)
                .addComponent(imgSair)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        lblAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                CadastroAluno alunoView = new CadastroAluno();
                alunoView.setVisible(true);
                CadastroTurmas.this.dispose();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlunos.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlunos.setForeground(Color.WHITE); // volta cor original
            }
        });
        lblTurmas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // Code adding the component to the parent container - not shown here
        lblTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                CadastroTurmas turmaView = new CadastroTurmas();
                turmaView.setVisible(true);
                CadastroTurmas.this.dispose();

            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTurmas.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTurmas.setForeground(Color.WHITE); // volta cor original
            }
        });
        imgSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // Code adding the component to the parent container - not shown here
        imgSair.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                LoginView loginView = new LoginView();
                loginView.setVisible(true);
                CadastroTurmas.this.dispose();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgSair.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgSair.setForeground(Color.WHITE); // volta cor original
            }
        });

        imgCoruja2.setText("coruja02");
        imgCoruja2.setMaximumSize(new java.awt.Dimension(150, 150));
        imgCoruja2.setMinimumSize(new java.awt.Dimension(150, 150));
        imgCoruja2.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel7.setText("Cadastro de Turmas");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Nome:");

        nomeFields.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeFields.setBorder(null);
        nomeFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldsActionPerformed(evt);
            }
        });

        salvarBtn.setBackground(new java.awt.Color(200, 162, 200));
        salvarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salvarBtn.setForeground(new java.awt.Color(255, 255, 255));
        salvarBtn.setText("Salvar");
        salvarBtn.setBorder(null);
        salvarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setBackground(new java.awt.Color(200, 162, 200));
        cancelarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelarBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBtn.setText("Cancelar");
        cancelarBtn.setBorder(null);
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        ButtonUtils.estilizarBotao(cancelarBtn);

        listarBtn.setBackground(new java.awt.Color(200, 162, 200));
        listarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listarBtn.setForeground(new java.awt.Color(255, 255, 255));
        listarBtn.setText("Listar Alunos");
        listarBtn.setBorder(null);
        listarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Alunos:");

        alunosPainel.setBackground(new java.awt.Color(255, 255, 255));
        alunosPainel.setForeground(new java.awt.Color(0, 0, 0));
        alunosPainel.setMinimumSize(new java.awt.Dimension(400, 250));
        alunosPainel.setPreferredSize(new java.awt.Dimension(400, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeFields, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(listarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imgCoruja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(98, 98, 98))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(salvarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alunosPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nomeFields, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alunosPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(imgCoruja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(listarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );

        TextFieldUtils.estilizarCampo(nomeFields);
        ButtonUtils.estilizarBotao(salvarBtn);
        ButtonUtils.estilizarBotao(listarBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void Salvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salvar2ActionPerformed

    private void Salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salvar1ActionPerformed

    private void Salvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salvar3ActionPerformed

    private void nomeFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldsActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        DashboardView dash = new DashboardView();
        dash.setVisible(true);
        CadastroTurmas.this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void listarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBtnActionPerformed
        // TODO add your handling code here:
        ListaTurmas turmas = new ListaTurmas();
        turmas.setVisible(true);
        CadastroTurmas.this.dispose();
    }//GEN-LAST:event_listarBtnActionPerformed

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        // TODO add your handling code here:
        String nomeTurma = nomeFields.getText().trim();

        if (nomeTurma.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o nome da turma!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1️⃣ Criar a turma
        Turma novaTurma = new Turma();
        novaTurma.setNome(nomeTurma);

        TurmaDao turmaDao = new TurmaDao();
        int novoIdTurma = turmaDao.salvarERetornarId(novaTurma);

        if (novoIdTurma <= 0) {
            JOptionPane.showMessageDialog(this, "Erro ao criar a turma!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int atualizados = 0;
        for (JCheckBox cb : checkboxes) {
            if (cb.isSelected()) {
                int idAluno = (int) cb.getClientProperty("id_aluno");

                // Busca o aluno atual
                AlunoDao alunoDao = new AlunoDao();
                Aluno aluno = alunoDao.buscarPorId(idAluno);

                if (aluno != null) {
                    aluno.setIdTurma(novoIdTurma);
                    boolean ok = AlunoDao.atualizarAluno(aluno);
                    if (ok) atualizados++;
                
            }
            }
        }
        JOptionPane.showMessageDialog(this,
                "Turma criada com sucesso!\nAlunos atualizados: " + atualizados,
                "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        nomeFields.setText("");
        preencherAlunos(); // recarrega a lista (remove os que mudaram de turma)
        
    }//GEN-LAST:event_salvarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTurmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salvar;
    private javax.swing.JButton Salvar1;
    private javax.swing.JButton Salvar2;
    private javax.swing.JButton Salvar3;
    private javax.swing.JPanel alunosPainel;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JLabel imgCoruja1;
    private javax.swing.JLabel imgCoruja2;
    private javax.swing.JLabel imgSair;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAlunos;
    private javax.swing.JLabel lblTurmas;
    private javax.swing.JButton listarBtn;
    private javax.swing.JTextField nomeFields;
    private javax.swing.JButton salvarBtn;
    // End of variables declaration//GEN-END:variables
}
