/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AlunoDao;
import dao.UsuarioDao;
import java.awt.BorderLayout;
import java.awt.*;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.*;
import model.Aluno;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.text.MaskFormatter;
import utils.ButtonUtils;
import utils.TextFieldUtils;
import view.listaAlunos;

/**
 *
 * @author lucelia
 */
public class CadastroAluno extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView
     */
    private Aluno alunoEmEdicao = null;
    public CadastroAluno() {
        initComponents();
        excluirBtn.setEnabled(false);
        configuracaoPadrao();
    }
    
    public CadastroAluno(Aluno aluno){
    initComponents();
    this.alunoEmEdicao = aluno;
    preencherCampos(aluno);
    excluirBtn.setEnabled(true); 
    
    configuracaoPadrao();
    }
    
   private void configuracaoPadrao(){
         setSize(800, 650);
        setLocationRelativeTo(null);
        
        getContentPane().setBackground(new Color(200,162,200));
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        ImageIcon sairIco = new ImageIcon(getClass().getResource("/img/sair.png"));
        ImageIcon corujaIcoLogo = new ImageIcon(getClass().getResource("/img/coruja.png"));
        ImageIcon corujaIco1 = new ImageIcon(getClass().getResource("/img/coruja01.png"));
        
        Image imgSairIco = sairIco.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        Image imgCorujaLogo = corujaIcoLogo.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        Image imgCorujaIco01 = corujaIco1.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        
        imgSair.setIcon(new ImageIcon(imgSairIco));
        
        imgCoruja1.setText(null);
        imgCoruja1.setIcon(new ImageIcon(imgCorujaLogo));
        
        
        imgCoruja2.setText(null);
       imgCoruja2.setIcon(new ImageIcon(imgCorujaIco01));

   }
    private void preencherCampos(Aluno aluno) {
    nomeField.setText(aluno.getNome());
    responsavelField.setText(aluno.getResponsavelNome());
    historicoTxtArea.setText(aluno.getHistoricoEscolar());
    
    if(aluno.getDataNascimento() != null){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        dtNascimentoField.setText(aluno.getDataNascimento().format(formatter));
    }else{
        dtNascimentoField.setText("");
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imgCoruja1 = new javax.swing.JLabel();
        lblAlunos = new javax.swing.JLabel();
        lblTurmas = new javax.swing.JLabel();
        imgSair = new javax.swing.JLabel();
        imgCoruja2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        responsavelField = new javax.swing.JTextField();
        dtNascimentoField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        historicoTxtArea = new javax.swing.JTextArea();
        salvarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        excluirBtn = new javax.swing.JButton();
        listarAlunosBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 219, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 219, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(200, 162, 200));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        imgCoruja1.setText("coruja01");
        imgCoruja1.setMaximumSize(new java.awt.Dimension(150, 150));
        imgCoruja1.setMinimumSize(new java.awt.Dimension(150, 150));
        imgCoruja1.setPreferredSize(new java.awt.Dimension(150, 150));

        lblAlunos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAlunos.setForeground(new java.awt.Color(255, 255, 255));
        lblAlunos.setText("Alunos");
        lblAlunos.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblTurmas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTurmas.setForeground(new java.awt.Color(255, 255, 255));
        lblTurmas.setText("Turmas");

        imgSair.setText("sair");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imgCoruja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imgCoruja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAlunos)
                .addGap(157, 157, 157)
                .addComponent(lblTurmas)
                .addGap(170, 170, 170)
                .addComponent(imgSair)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        lblAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                CadastroAluno alunoView = new CadastroAluno();
                alunoView.setVisible(true);
                CadastroAluno.this.dispose();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlunos.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlunos.setForeground(Color.WHITE); // volta cor original
            }
        });
        lblTurmas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // Code adding the component to the parent container - not shown here
        lblTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                CadastroTurmas turmaView = new CadastroTurmas();
                turmaView.setVisible(true);
                CadastroAluno.this.dispose();

            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTurmas.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTurmas.setForeground(Color.WHITE); // volta cor original
            }
        });
        imgSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // Code adding the component to the parent container - not shown here
        imgSair.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                LoginView loginView = new LoginView();
                loginView.setVisible(true);
                CadastroAluno.this.dispose();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgSair.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgSair.setForeground(Color.WHITE); // volta cor original
            }
        });

        imgCoruja2.setText("coruja02");
        imgCoruja2.setMaximumSize(new java.awt.Dimension(150, 150));
        imgCoruja2.setMinimumSize(new java.awt.Dimension(150, 150));
        imgCoruja2.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel3.setText("Cadastro de Alunos");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Responsavel:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Nome:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Data de Nascimento:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Historico:");

        nomeField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeField.setBorder(null);
        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });

        responsavelField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        responsavelField.setBorder(null);

        dtNascimentoField.setBorder(null);
        dtNascimentoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        historicoTxtArea.setColumns(20);
        historicoTxtArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        historicoTxtArea.setRows(5);
        historicoTxtArea.setBorder(null);
        jScrollPane1.setViewportView(historicoTxtArea);

        salvarBtn.setBackground(new java.awt.Color(200, 162, 200));
        salvarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salvarBtn.setForeground(new java.awt.Color(255, 255, 255));
        salvarBtn.setText("Salvar");
        salvarBtn.setBorder(null);
        salvarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setBackground(new java.awt.Color(200, 162, 200));
        cancelarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelarBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBtn.setText("Cancelar");
        cancelarBtn.setBorder(null);
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        excluirBtn.setBackground(new java.awt.Color(200, 162, 200));
        excluirBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        excluirBtn.setForeground(new java.awt.Color(255, 255, 255));
        excluirBtn.setText("Excluir");
        excluirBtn.setBorder(null);
        excluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBtnActionPerformed(evt);
            }
        });

        listarAlunosBtn.setBackground(new java.awt.Color(200, 162, 200));
        listarAlunosBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listarAlunosBtn.setForeground(new java.awt.Color(255, 255, 255));
        listarAlunosBtn.setText("Listar Alunos");
        listarAlunosBtn.setBorder(null);
        listarAlunosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarAlunosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(listarAlunosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgCoruja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(salvarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(excluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dtNascimentoField)
                                    .addComponent(nomeField)
                                    .addComponent(responsavelField, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(dtNascimentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(responsavelField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(imgCoruja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(listarAlunosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        TextFieldUtils.estilizarCampo(nomeField);
        TextFieldUtils.estilizarCampo(responsavelField);
        try {
            MaskFormatter maskData = new MaskFormatter("##-##-####");
            maskData.install(dtNascimentoField);
        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }
        TextFieldUtils.estilizarCampo(dtNascimentoField);
        ButtonUtils.estilizarBotao(salvarBtn);
        ButtonUtils.estilizarBotao(cancelarBtn);
        ButtonUtils.estilizarBotao(excluirBtn);
        ButtonUtils.estilizarBotao(listarAlunosBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        DashboardView dashboard = new DashboardView();
        dashboard.setVisible(true);
        CadastroAluno.this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void excluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBtnActionPerformed
        // TODO add your handling code here:
        if (alunoEmEdicao == null) {
        JOptionPane.showMessageDialog(this, "Nenhum aluno selecionado para exclusão!");
        return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este aluno?", 
                                                    "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            AlunoDao.excluirAluno(alunoEmEdicao.getIdAluno());
            JOptionPane.showMessageDialog(this, "Aluno excluído com sucesso!");
            this.dispose();
        }
    }//GEN-LAST:event_excluirBtnActionPerformed

    private void listarAlunosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarAlunosBtnActionPerformed
        // TODO add your handling code here:
        
         listaAlunos alunos = new listaAlunos();
        alunos.setVisible(true);
        CadastroAluno.this.dispose();
                                         
    }//GEN-LAST:event_listarAlunosBtnActionPerformed

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        // TODO add your handling code here:
         try {
             DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            String dataTexto = dtNascimentoField.getText().trim(); // formato: yyyy-MM-dd
            LocalDate dataNascimento;
             try {
                 dataNascimento = LocalDate.parse(dataTexto, formatter);
             } catch (DateTimeParseException e) {
                 JOptionPane.showMessageDialog(this, "Data inválida! use o formato DD-MM-AAAA (Ex: 14-05-2015)", "Erro de formato", JOptionPane.ERROR_MESSAGE);
                 return;
             }
             
            String nomeAluno = nomeField.getText().trim();
            String nomeResponsavel = responsavelField.getText().trim();

            if (nomeAluno.isEmpty() || nomeResponsavel.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Preencha o nome do aluno e do responsável.",
                    "Campos obrigatórios", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            UsuarioDao usuarioDAO = new UsuarioDao();
            Integer idResponsavel = usuarioDAO.buscarUsuarioPorLogin(nomeResponsavel);

            if (idResponsavel == null) {
                // Se não existe, cria um novo usuário Pai
                idResponsavel = usuarioDAO.criarUsuarioPai(nomeResponsavel, nomeAluno);
                JOptionPane.showMessageDialog(this, 
                    "Novo responsável criado: " + nomeResponsavel,
                    "Usuário Pai Criado", JOptionPane.INFORMATION_MESSAGE);
            }

            Aluno aluno = new Aluno();
            aluno.setNome(nomeAluno);
            aluno.setDataNascimento(dataNascimento);
            aluno.setHistoricoEscolar(historicoTxtArea.getText());

            // Exemplo: vamos assumir que o responsável e a turma serão definidos fixos ou virão de campos escondidos
            aluno.setIdResponsavel(idResponsavel); //
            aluno.setIdTurma(1); 
// 
            if (alunoEmEdicao == null){            
                AlunoDao dao = new AlunoDao();               
                dao.salvarAluno(aluno);
            }
            else
            {
                aluno.setIdAluno(alunoEmEdicao.getIdAluno());
                boolean atualizar = AlunoDao.atualizarAluno(aluno);
                if (atualizar){
                    System.out.println("Aluno Atualizado com sucesso!");
                }else{
                    System.out.println("Erro ao atualizar!");
                }
            }

            // Limpa os campos
            nomeField.setText("");
            dtNascimentoField.setText("");
            historicoTxtArea.setText("");
            responsavelField.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }        
    }//GEN-LAST:event_salvarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JFormattedTextField dtNascimentoField;
    private javax.swing.JButton excluirBtn;
    private javax.swing.JTextArea historicoTxtArea;
    private javax.swing.JLabel imgCoruja1;
    private javax.swing.JLabel imgCoruja2;
    private javax.swing.JLabel imgSair;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlunos;
    private javax.swing.JLabel lblTurmas;
    private javax.swing.JButton listarAlunosBtn;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField responsavelField;
    private javax.swing.JButton salvarBtn;
    // End of variables declaration//GEN-END:variables
}
