/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AlunoDao;
import java.awt.BorderLayout;
import java.awt.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import model.Aluno;
import utils.ButtonUtils;

/**
 *
 * @author lucelia
 */
public class listaAlunos extends javax.swing.JFrame {

    public listaAlunos() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) alunosTable.getModel();
        model.addColumn("ID"); 
        
        setSize(800, 650);
        setLocationRelativeTo(null);
        
        getContentPane().setBackground(new Color(200,162,200));
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        ImageIcon sairIco = new ImageIcon(getClass().getResource("/img/sair.png"));
        ImageIcon corujaIcoLogo = new ImageIcon(getClass().getResource("/img/coruja.png"));
        ImageIcon corujaIco1 = new ImageIcon(getClass().getResource("/img/coruja01.png"));
        ImageIcon editIcon = new ImageIcon(getClass().getResource("/img/edit.png"));
        ImageIcon deletIco = new ImageIcon(getClass().getResource("/img/delete.png"));
        
        
        
        Image imgSairIco = sairIco.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        Image imgCorujaLogo = corujaIcoLogo.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        Image imgCorujaIco01 = corujaIco1.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        Image imgEditIco = editIcon.getImage().getScaledInstance(37, 37, Image.SCALE_SMOOTH);
        Image imgDeleteIco = deletIco.getImage().getScaledInstance(37, 37, Image.SCALE_SMOOTH);
        
        imgSair.setIcon(new ImageIcon(imgSairIco));
        
        imgCoruja1.setText(null);
        imgCoruja1.setIcon(new ImageIcon(imgCorujaLogo));
        
        
        imgCoruja2.setText(null);
       imgCoruja2.setIcon(new ImageIcon(imgCorujaIco01));
       
       
       txtBtnEditar.setIcon(new ImageIcon(imgEditIco));
        
       excluirTextBtn.setIcon(new ImageIcon(imgDeleteIco));
    
       preencherTabela();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imgCoruja1 = new javax.swing.JLabel();
        imgSair = new javax.swing.JLabel();
        lblTurmas = new javax.swing.JLabel();
        lblAlunos = new javax.swing.JLabel();
        imgCoruja2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alunosTable = new javax.swing.JTable();
        excluirTextBtn = new javax.swing.JLabel();
        txtBtnEditar = new javax.swing.JLabel();
        btnCadastrarAlunos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 219, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 219, 255));

        jPanel2.setBackground(new java.awt.Color(200, 162, 200));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        imgCoruja1.setText("coruja01");
        imgCoruja1.setMaximumSize(new java.awt.Dimension(150, 150));
        imgCoruja1.setMinimumSize(new java.awt.Dimension(150, 150));
        imgCoruja1.setPreferredSize(new java.awt.Dimension(150, 150));

        imgSair.setText("sair");

        lblTurmas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTurmas.setForeground(new java.awt.Color(255, 255, 255));
        lblTurmas.setText("Turmas");

        lblAlunos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAlunos.setForeground(new java.awt.Color(255, 255, 255));
        lblAlunos.setText("Alunos");
        lblAlunos.setCursor(new Cursor(Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imgCoruja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imgCoruja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAlunos)
                .addGap(157, 157, 157)
                .addComponent(lblTurmas)
                .addGap(170, 170, 170)
                .addComponent(imgSair)
                .addContainerGap(647, Short.MAX_VALUE))
        );

        imgSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // Code adding the component to the parent container - not shown here
        imgSair.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                LoginView loginView = new LoginView();
                loginView.setVisible(true);
                listaAlunos.this.dispose();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgSair.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgSair.setForeground(Color.WHITE); // volta cor original
            }
        });
        lblTurmas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // Code adding the component to the parent container - not shown here
        lblTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                CadastroTurmas turmaView = new CadastroTurmas();
                turmaView.setVisible(true);
                listaAlunos.this.dispose();

            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTurmas.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTurmas.setForeground(Color.WHITE); // volta cor original
            }
        });
        lblAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                CadastroAluno alunoView = new CadastroAluno();
                alunoView.setVisible(true);
                listaAlunos.this.dispose();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlunos.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlunos.setForeground(Color.WHITE); // volta cor original
            }
        });

        imgCoruja2.setText("coruja02");
        imgCoruja2.setMaximumSize(new java.awt.Dimension(150, 150));
        imgCoruja2.setMinimumSize(new java.awt.Dimension(150, 150));
        imgCoruja2.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel3.setText("Lista de Alunos");

        alunosTable.setBackground(new java.awt.Color(200, 162, 200));
        alunosTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alunosTable.setForeground(new java.awt.Color(0, 0, 0));
        alunosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Nome", "Turma"
            }
        ));
        jScrollPane1.setViewportView(alunosTable);

        excluirTextBtn.setText("Excluir");
        excluirTextBtn.setMaximumSize(new java.awt.Dimension(45, 45));
        excluirTextBtn.setMinimumSize(new java.awt.Dimension(42, 42));
        excluirTextBtn.setPreferredSize(new java.awt.Dimension(42, 42));

        txtBtnEditar.setText("Editar");
        txtBtnEditar.setMaximumSize(new java.awt.Dimension(45, 45));
        txtBtnEditar.setMinimumSize(new java.awt.Dimension(42, 42));
        txtBtnEditar.setPreferredSize(new java.awt.Dimension(42, 42));

        btnCadastrarAlunos.setBackground(new java.awt.Color(200, 162, 200));
        btnCadastrarAlunos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarAlunos.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarAlunos.setText("Cadastrar Alunos");
        btnCadastrarAlunos.setBorder(null);
        btnCadastrarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlunosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 157, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(157, 157, 157))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCadastrarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addComponent(excluirTextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(imgCoruja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addComponent(imgCoruja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excluirTextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(596, 596, 596))
        );

        excluirTextBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        excluirTextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = alunosTable.getSelectedRow();
                if (selectedRow == -1) {
                    JOptionPane.showMessageDialog(null,
                        "Selecione um aluno para excluir.",
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                int confirm = JOptionPane.showConfirmDialog(
                    null,
                    "Tem certeza que deseja excluir este aluno?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION
                );

                if (confirm == JOptionPane.YES_OPTION) {
                    int idAluno = Integer.parseInt(alunosTable.getValueAt(selectedRow, 0).toString());
                    boolean sucesso = AlunoDao.excluirAluno(idAluno);

                    if (sucesso) {
                        JOptionPane.showMessageDialog(null,
                            "Aluno excluído com sucesso!",
                            "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                        preencherTabela(); // Atualiza a tabela
                    } else {
                        JOptionPane.showMessageDialog(null,
                            "Erro ao excluir aluno.",
                            "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                excluirTextBtn.setForeground(Color.RED);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                excluirTextBtn.setForeground(Color.BLACK);
            }
        });
        txtBtnEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        txtBtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int linhaSelecionada = alunosTable.getSelectedRow();
                if (linhaSelecionada == -1) {
                    JOptionPane.showMessageDialog(null, "Selecione um aluno para editar!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // Supondo que a primeira coluna seja o ID ou o nome do aluno
                String nomeAluno = alunosTable.getValueAt(linhaSelecionada, 0).toString();

                AlunoDao dao = new AlunoDao();
                Aluno aluno = dao.buscarPorNome(nomeAluno);

                CadastroAluno cadastroView = new CadastroAluno(aluno);
                cadastroView.setVisible(true);
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnEditar.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnEditar.setForeground(Color.BLACK); // volta cor original
            }
        });
        ButtonUtils.estilizarBotao(btnCadastrarAlunos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlunosActionPerformed
        // TODO add your handling code here:
        CadastroAluno alunosCad = new CadastroAluno();
        alunosCad.setVisible(true);
        listaAlunos.this.dispose();
    }//GEN-LAST:event_btnCadastrarAlunosActionPerformed
    public void preencherTabela() {
        String[] colunas = {"ID","Nome", "Turma"};
        DefaultTableModel model = new DefaultTableModel(colunas, 0); 

        AlunoDao alunoDao = new AlunoDao();
        List<String[]> lista = alunoDao.listarAlunosComTurma();

        for (String[] dados : lista) {
            model.addRow(dados);
        }

        alunosTable.setModel(model);
        alunosTable.getColumnModel().getColumn(0).setMinWidth(0);
        alunosTable.getColumnModel().getColumn(0).setMaxWidth(0);
        alunosTable.getColumnModel().getColumn(0).setWidth(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alunosTable;
    private javax.swing.JButton btnCadastrarAlunos;
    private javax.swing.JLabel excluirTextBtn;
    private javax.swing.JLabel imgCoruja1;
    private javax.swing.JLabel imgCoruja2;
    private javax.swing.JLabel imgSair;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlunos;
    private javax.swing.JLabel lblTurmas;
    private javax.swing.JLabel txtBtnEditar;
    // End of variables declaration//GEN-END:variables
}
