/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.TurmaDao;
import model.Turma;
import java.awt.BorderLayout;
import java.awt.*;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import utils.ButtonUtils;
import java.util.List;


/**
 *
 * @author lucelia
 */
public class ListaTurmas extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView
     */
    public ListaTurmas() {
        initComponents();
        setSize(800, 650);
        setLocationRelativeTo(null);
        
        getContentPane().setBackground(new Color(200,162,200));
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        ImageIcon sairIco = new ImageIcon(getClass().getResource("/img/sair.png"));
        ImageIcon corujaIcoLogo = new ImageIcon(getClass().getResource("/img/coruja.png"));
        ImageIcon corujaIco1 = new ImageIcon(getClass().getResource("/img/coruja01.png"));
        
        Image imgSairIco = sairIco.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        Image imgCorujaLogo = corujaIcoLogo.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        Image imgCorujaIco01 = corujaIco1.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        
        imgSair.setIcon(new ImageIcon(imgSairIco));
        
        imgCoruja1.setText(null);
        imgCoruja1.setIcon(new ImageIcon(imgCorujaLogo));
        
        
        imgCoruja2.setText(null);
       imgCoruja2.setIcon(new ImageIcon(imgCorujaIco01));
       
        ImageIcon editIcon = new ImageIcon(getClass().getResource("/img/edit.png"));
        ImageIcon deletIco = new ImageIcon(getClass().getResource("/img/delete.png"));
        
        Image imgEditIco = editIcon.getImage().getScaledInstance(37, 37, Image.SCALE_SMOOTH);
        Image imgDeleteIco = deletIco.getImage().getScaledInstance(37, 37, Image.SCALE_SMOOTH);
        
        txtBtnEditar.setIcon(new ImageIcon(imgEditIco));
        
        excluirTextBtn.setIcon(new ImageIcon(imgDeleteIco));
        
         DefaultTableModel model = (DefaultTableModel) turmasTable.getModel();
        
        turmasTable.getColumnModel().getColumn(0).setMinWidth(0);
        turmasTable.getColumnModel().getColumn(0).setMaxWidth(0);
        turmasTable.getColumnModel().getColumn(0).setWidth(0);
        preencherTabela();
    }
    
      private void preencherTabela() {
    DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nome da Turma"}, 0);

    TurmaDao turmaDao = new TurmaDao();
    List<Turma> turmas = turmaDao.listarTodas();

    for (Turma t : turmas) {
        model.addRow(new Object[]{t.getIdTurma(), t.getNome()});
        System.out.println("turma:" + t);
    }

    turmasTable.setModel(model);

    // Ocultar coluna ID novamente (por precaução)
    turmasTable.getColumnModel().getColumn(0).setMinWidth(0);
    turmasTable.getColumnModel().getColumn(0).setMaxWidth(0);
    turmasTable.getColumnModel().getColumn(0).setWidth(0);
}
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imgCoruja1 = new javax.swing.JLabel();
        imgSair = new javax.swing.JLabel();
        lblTurmas = new javax.swing.JLabel();
        lblAlunos = new javax.swing.JLabel();
        imgCoruja2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        turmasTable = new javax.swing.JTable();
        txtBtnEditar = new javax.swing.JLabel();
        excluirTextBtn = new javax.swing.JLabel();
        cadastrarAlunosBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 219, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 219, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 650));

        jPanel2.setBackground(new java.awt.Color(200, 162, 200));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        imgCoruja1.setText("coruja01");
        imgCoruja1.setMaximumSize(new java.awt.Dimension(150, 150));
        imgCoruja1.setMinimumSize(new java.awt.Dimension(150, 150));
        imgCoruja1.setPreferredSize(new java.awt.Dimension(150, 150));

        imgSair.setText("sair");

        lblTurmas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTurmas.setForeground(new java.awt.Color(255, 255, 255));
        lblTurmas.setText("Turmas");

        lblAlunos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAlunos.setForeground(new java.awt.Color(255, 255, 255));
        lblAlunos.setText("Alunos");
        lblAlunos.setCursor(new Cursor(Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imgCoruja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imgCoruja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAlunos)
                .addGap(157, 157, 157)
                .addComponent(lblTurmas)
                .addGap(170, 170, 170)
                .addComponent(imgSair)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        imgSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // Code adding the component to the parent container - not shown here
        imgSair.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                LoginView loginView = new LoginView();
                loginView.setVisible(true);
                ListaTurmas.this.dispose();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgSair.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgSair.setForeground(Color.WHITE); // volta cor original
            }
        });
        lblTurmas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // Code adding the component to the parent container - not shown here
        lblTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                CadastroTurmas turmaView = new CadastroTurmas();
                turmaView.setVisible(true);
                ListaTurmas.this.dispose();

            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTurmas.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTurmas.setForeground(Color.WHITE); // volta cor original
            }
        });
        lblAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Código que abre a tela de Alunos
                CadastroAluno alunoView = new CadastroAluno();
                alunoView.setVisible(true);
                ListaTurmas.this.dispose();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlunos.setForeground(Color.RED); // efeito hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlunos.setForeground(Color.WHITE); // volta cor original
            }
        });

        imgCoruja2.setText("coruja02");
        imgCoruja2.setMaximumSize(new java.awt.Dimension(150, 150));
        imgCoruja2.setMinimumSize(new java.awt.Dimension(150, 150));
        imgCoruja2.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel3.setText("Lista de Turmas");

        turmasTable.setBackground(new java.awt.Color(200, 162, 200));
        turmasTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        turmasTable.setForeground(new java.awt.Color(0, 0, 0));
        turmasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Turma"
            }
        ));
        jScrollPane1.setViewportView(turmasTable);

        txtBtnEditar.setText("Editar");
        txtBtnEditar.setMaximumSize(new java.awt.Dimension(45, 45));
        txtBtnEditar.setMinimumSize(new java.awt.Dimension(42, 42));
        txtBtnEditar.setPreferredSize(new java.awt.Dimension(42, 42));

        excluirTextBtn.setText("Excluir");
        excluirTextBtn.setMaximumSize(new java.awt.Dimension(45, 45));
        excluirTextBtn.setMinimumSize(new java.awt.Dimension(42, 42));
        excluirTextBtn.setPreferredSize(new java.awt.Dimension(42, 42));
        excluirTextBtn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                excluirTextBtnAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cadastrarAlunosBtn.setBackground(new java.awt.Color(200, 162, 200));
        cadastrarAlunosBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarAlunosBtn.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarAlunosBtn.setText("Cadastrar Alunos");
        cadastrarAlunosBtn.setBorder(null);
        cadastrarAlunosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlunosBtnActionPerformed(evt);
            }
        });
        ButtonUtils.estilizarBotao(cadastrarAlunosBtn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 175, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(142, 142, 142))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cadastrarAlunosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(excluirTextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgCoruja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(excluirTextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cadastrarAlunosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(imgCoruja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        txtBtnEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        txtBtnEditar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int linhaSelecionada = turmasTable.getSelectedRow();

                if (linhaSelecionada == -1) {
                    JOptionPane.showMessageDialog(null, "Selecione uma turma para editar!");
                    return;
                }

                int idTurma = (int) turmasTable.getValueAt(linhaSelecionada, 0);
                TurmaDao dao = new TurmaDao();
                Turma turma = dao.buscarPorId(idTurma);

                if (turma != null) {
                    CadastroTurmas telaEdicao = new CadastroTurmas(turma);
                    telaEdicao.setVisible(true);
                    dispose(); // fecha a tela atual, se quiser
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao carregar turma para edição!");
                }
            }
        });
        excluirTextBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        excluirTextBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int linhaSelecionada = turmasTable.getSelectedRow();

                if (linhaSelecionada == -1) {
                    JOptionPane.showMessageDialog(null, "Selecione uma turma para excluir!");
                    return;
                }

                // Pega o id da turma (mesmo estando oculto)
                int idTurma = (int) turmasTable.getValueAt(linhaSelecionada, 0);

                int confirm = JOptionPane.showConfirmDialog(null,
                    "Deseja realmente excluir esta turma?", "Confirmação", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    TurmaDao dao = new TurmaDao();
                    boolean sucesso = dao.deletar(idTurma);

                    if (sucesso) {
                        JOptionPane.showMessageDialog(null, "Turma excluída com sucesso!");
                        preencherTabela(); // Atualiza a tabela
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ao excluir turma!");
                    }
                }
            }
        });

        excluirTextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int linhaSelecionada = turmasTable.getSelectedRow();
                if (linhaSelecionada == -1) {
                    JOptionPane.showMessageDialog(null, "Selecione uma turma para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                int idTurma = (int) turmasTable.getValueAt(linhaSelecionada, 0);
                String nomeTurma = (String) turmasTable.getValueAt(linhaSelecionada, 1);

                int confirm = JOptionPane.showConfirmDialog(null,
                    "Tem certeza que deseja excluir a turma \"" + nomeTurma + "\"?\n" +
                    "Os alunos serão movidos para a turma padrão (ID 1).",
                    "Confirmar exclusão",
                    JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    TurmaDao dao = new TurmaDao();
                    boolean sucesso = dao.excluirTurmaComAlunos(idTurma);

                    if (sucesso) {
                        JOptionPane.showMessageDialog(null, "Turma excluída com sucesso!");
                        preencherTabela(); // atualiza a tabela de turmas
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ao excluir turma.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarAlunosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlunosBtnActionPerformed
        // TODO add your handling code here:
        CadastroTurmas cadastro = new CadastroTurmas();
        cadastro.setVisible(true);
        ListaTurmas.this.dispose();
    }//GEN-LAST:event_cadastrarAlunosBtnActionPerformed

    private void excluirTextBtnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_excluirTextBtnAncestorAdded
        // TODO add your handling code here:
            
        
    }//GEN-LAST:event_excluirTextBtnAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaTurmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarAlunosBtn;
    private javax.swing.JLabel excluirTextBtn;
    private javax.swing.JLabel imgCoruja1;
    private javax.swing.JLabel imgCoruja2;
    private javax.swing.JLabel imgSair;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlunos;
    private javax.swing.JLabel lblTurmas;
    private javax.swing.JTable turmasTable;
    private javax.swing.JLabel txtBtnEditar;
    // End of variables declaration//GEN-END:variables
}
