/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UsuarioDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.io.InputStream;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Usuario;


/**
 *
 * @author lucelia
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        setSize(650, 600);
        setLocationRelativeTo(null);
        setResizable(false);
        
       // getContentPane().removeAll();
        //getContentPane().setLayout(new BorderLayout());
        
        getContentPane().setBackground(new Color(200,162,200));
        
        try{
            try (InputStream is = getClass().getResourceAsStream("/font/IngridDarling-Regular.ttf"))
            {
             if( is == null){
                 System.err.println("Fonte não encontrada no classpath!");
                 tituloJlabel.setFont(new Font("Serif", Font.BOLD, 36));
             } else{
                 Font ingrid = Font.createFont(Font.TRUETYPE_FONT,is);
                GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                ge.registerFont(ingrid);
                Font titleFont = ingrid.deriveFont(Font.PLAIN, 80f);
                tituloJlabel.setFont(titleFont);
                tituloJlabel.setForeground(Color.WHITE);
                tituloJlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                
                
             };   
            } catch (Exception e) {
                e.printStackTrace();
                
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
            tituloJlabel.setFont(new Font("Serif", Font.BOLD, 36));
        }
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/coruja.png"));
        Image img = icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        imgLabel.setText(null);
        imgLabel.setIcon(new ImageIcon(img));
        
        AffineTransform tx = AffineTransform.getScaleInstance(-1,1);
        tx.translate(-img.getWidth(null),0);
        
        BufferedImage bufferedImg = new BufferedImage(img.getWidth(null),img.getHeight(null),BufferedImage.TYPE_INT_ARGB);
        
        Graphics2D g2d = bufferedImg.createGraphics();
        g2d.drawImage(img, tx, null);
        g2d.dispose();
        
        imgreverseLabel.setText(null);
        imgreverseLabel.setIcon(new ImageIcon(bufferedImg));
        
        
       /* JPanel painelLogin = new JPanel(new GridBagLayout());

        painelLogin.setBackground(new java.awt.Color(200, 162, 200));

        painelLogin.setForeground(new java.awt.Color(200, 162, 200));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10,10,10,10);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        // Code of sub-components - not shown here
        gbc.gridx= 1;
        gbc.gridy = 0;
        painelLogin.add(new JLabel("Login"), gbc);

        gbc.gridx= 1;
        gbc.gridy = 1;
        painelLogin.add(new JTextField(15), gbc);
        // Code of sub-components - not shown here
        gbc.gridx= 1;
        gbc.gridy = 2;
        painelLogin.add(new JLabel("Senha"), gbc);

        gbc.gridx= 1;
        gbc.gridy = 3;
        painelLogin.add(new JTextField(15), gbc);

        gbc.gridx= 1;
        gbc.gridy = 4;
        gbc.gridwidth = 1;
        gbc.anchor = GridBagConstraints.CENTER;
        painelLogin.add(new JButton("Entrar"), gbc);
        
        
        //getContentPane().add(painelLogin, BorderLayout.CENTER);
       painelLogin.setBounds(150,200,300,400);
       getContentPane().add(painelLogin);
// Layout setup code - not shown here
        */

// Code adding the component to the parent container - not shown here

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJlabel = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        imgreverseLabel = new javax.swing.JLabel();
        txtLogin = new javax.swing.JLabel();
        txtSenha = new javax.swing.JLabel();
        fieldLogin = new javax.swing.JTextField();
        fieldSenha = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 600));

        tituloJlabel.setText("<html><center>Pequena<br>Coruja</center></html>");
        tituloJlabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        imgLabel.setText("jLabel1");

        imgreverseLabel.setText("jLabel1");

        txtLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setText("Login");

        txtSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setText("Senha");

        fieldLogin.setBorder(null);
        fieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLoginActionPerformed(evt);
            }
        });

        fieldSenha.setBorder(null);

        jToggleButton1.setBackground(new java.awt.Color(106, 13, 145));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Entrar");
        jToggleButton1.setBorder(null);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgreverseLabel))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloJlabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 214, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtLogin))
                                    .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(181, 181, 181))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldLogin)
                                .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(212, 212, 212))))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgLabel)
                    .addComponent(imgreverseLabel))
                .addGap(10, 10, 10)
                .addComponent(tituloJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin)
                .addGap(5, 5, 5)
                .addComponent(fieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLoginActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String login = fieldLogin.getText();
        String senha = new String(fieldSenha.getPassword());

        UsuarioDao usuarioDAO = new UsuarioDao();
        Usuario usuario = usuarioDAO.autenticar(login, senha);

        if (usuario != null) {
            // Login válido, abre Dashboard
            DashboardView dashboard = new DashboardView();
            dashboard.setVisible(true);
            this.dispose(); // fecha tela de login
        } else {
            // Login inválido, exibe mensagem vermelha
            lblMensagem.setText("Login ou senha inexistente/errado");
            lblMensagem.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldLogin;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel imgreverseLabel;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel tituloJlabel;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtSenha;
    // End of variables declaration//GEN-END:variables
}
